### ISSUE TITLE
Why is there a loop in azurewadtableinput

### ISSUE THREAD

**Issue by EmFl** [Azure/azure-diagnostics-tools#21]
Can someone please explain this ?

When I run logstash in debug mode I see a huge query every seconds (I have at least 14 wadtableinput running in parallel so this adds up), looking at the code, I see this : 
 
query_filter = "(PartitionKey gt '#{partitionkey_from_datetime(@last_timestamp)}')"
    for i in 0..99
      query_filter << " or (PartitionKey gt '#{i.to_s.rjust(19, '0')}___#{partitionkey_from_datetime(@last_timestamp)}' and PartitionKey lt '#{i.to_s.rjust(19, '0')}___9999999999999999999')"
end # for block

What is the goal of the loop ?

Thanks

**Comment by whiskeyjay** [comment]
When the event volume is set to "Medium" or "Large" in the Azure Diagnostics configuration, the partition key will be in the format of "9999999999999999999___9999999999999999999", where the first part of numbers can be anywhere from 0 to 99, and second part of the numbers is the timestamp. Since the plug-in doesn't know the diagnostics configuration (which can be changed while LogStash is running), it tries to put all possible partition keys in the query, hence the loop.
