### ISSUE TITLE
Duplicate events

### ISSUE THREAD

**Issue by mbnshtck** [Azure/azure-diagnostics-tools#37]
the current implementation of querying the wad tables create a lot of duplicated events due to to the required  rounding of @last_timestamp to a 1 minute resolution (PartitionKey resolution). It is a major issues when the target destination is a storage that is less tolerable to duplicates (do not detect, and accepts duplicates). My suggestion is to filter the result of the query to the exact value @last_timestamp (to push only events that their TIMESTAMP property is GT than @last_timestamp).  Note: Maybe the RowIndex is a better second level filter?

**Comment by mbnshtck** [comment]
I checked it, and didn't see duplicates, not clear to me why? maybe it is because the TIMESTAMP resolution is minutes, and its value is the next minute? if this is the case. there is a possibility that we skip rows ? How TIMESTAMP is set?

**Comment by lmolkova** [comment]
The plugin executes each query once. It requests _@entity_count_to_process_ rows only. Is there are more, _@continuation_token_ is not nil and the same query continues until all rows for the requested time range are fetched.
Once _@contintuation_token_ is _nil_, _@last_timestamp_ and _@until_timastamp_ are updated, so the new query starts. And it does not overlap with previous one since _@last_timestamp_ should be equal to _@until_timestamp_ from the previous query and the query is built with _lt_. So, implemented algorithm should not produce duplicates.
It may however skip some rows if they are written after @data_latency_minutes minute delay. 
TIMESTAMP is written by MA agent and corresponds to the minute when event happened on server.

**Comment by clguimanMSFT** [comment]
@mbnshtck Can you please build and use the code in PR #98?  This will cache query results and make sure there are no duplicates or missing data.

**Comment by clguimanMSFT** [comment]
@mbnshtck version 0.9.12 has some extra checks for duplicate detection. Please reopen the issue if you still have problems
