### ISSUE TITLE
Duplicate values on Nordes fork

### ISSUE THREAD

**Issue by etoykan** [Azure/azure-diagnostics-tools#56]
Values are getting duplicated on high load. I don't know if it has something to do with the high load but usually it works just fine. When this error occurs I delete all the blob logs and change the sincedb name from config file and it works again.

![err](https://cloud.githubusercontent.com/assets/3639468/21112260/d3e5813c-c0ad-11e6-8177-4413527c2cfb.JPG)

Real record count is around 4k per minute but there is more than 16k records at 11:30 on elastic.

It looks like it starts over from the beginning for a period of 10 minutes, so every iteration increments the record count.

Update: The problem occurs when we swap deployment slot with the production one. I think sincedb gets broken somehow.

**Comment by simonwh** [comment]
@etoykan Having the same problem? Did you manage to find a solution?

The Azure original repo logstash blob plugin is basicly useless. Nordes fixes some issues, but we the duplicates are still a big problem. I get up to 10-15 duplicate rows. Swapping slots might be part of the problem.

Since blobs are the only way (besides filesystem) to get web logs from Azure Web Apps, we need a way to get the blob logs to somewhere else. Are there other solutions than this logstash plugin that is not really working? What are other people doing? :)

**Comment by etoykan** [comment]
@simonwh Unfortunately I haven't found any solution. It still happens but just a couple  of times a week so I can tolerate it since I don't have any other option.

I'm wondering about other people too, I think they just don't stash their logs :) or there  might be some other low level solution.

**Comment by simonwh** [comment]
@etoykan Alright, that's too bad. It happens a lot for me, for some reason.

And since this repo is basicly dead when it comes to this plugin, I decided to make a fork. Rebase with Nordes fixes. And cherry-pick [this commit](https://github.com/EmFl/azure-diagnostics-tools/commit/86bc7326e7aa32d4218afc2da91f0644893796dd) which fixes an offset spelling error that might be related to the issue we see. So deploying this now and we will see if it helps.

Would be great if the Azure team could contribute a few more resources to making this actually work, now that file system (not an option) and blob storage is the only way to get webserver logs from web apps!

**Comment by etoykan** [comment]
Hey @simonwh 
Have you found any solution? :)

**Comment by EmFl** [comment]
Hello,
we are having this issue as well and have started investigating on our side. I'll update if we find anything.

**Comment by simonwh** [comment]
@etoykan I never managed to find a good solution. What I explained above wasn't enough - I ran into another issue:

I have start_position set to "end" (the default). When the code encounters a new blob, it sets entity["byteOffset"] to blob_info.content_length. Then it requests blob content from content length entity["byteOffset"] to blob_info.content_length. Azure throws an exception because you are querying for the same start and end byte, ex from 2643 to 2643. Exception is thrown in the code, and the loop starts over never getting pass this stage.

Tried some quick fixes that didn't work well at the time, and never had time to look more into it. I practically gave up on collecting the IIS logs, which is a shame.

@EmFl Please update us if you find a solution :-)

**Comment by EmFl** [comment]
@simonwh I think I fixed your first issue like this :
```
 if entity['ETag'] == blob_info.properties[:etag]
          # nothing to do...
          # @logger.info("#{DateTime.now} Blob already up to date #{blob_info.name}")
        elsif entity['ByteOffset'] == blob_info.properties[:content_length]
          entity["ETag"] = blob_info.properties[:etag]
          @azure_table.insert_or_merge_entity(@sincedb, entity)
        else
```

Not sure I commited those changes yet somewhere

**Comment by simonwh** [comment]
@EmFl Thanks for your suggestion, will try it out. I remember trying something similar, but it's been a month since a looked at it last time. Will give it a go again 👍

**Comment by xiaomi7732** [comment]
Hi @simonwh,
Would you mind give logstash-input-azureblobs 0.9.8 a try? I think the new implementation should sort this issue out. Feel free to re-open this issue if that is not the case.

**Comment by simonwh** [comment]
@xiaomi7732 Hi! Sorry for the (very late) reply. I've been looking at your new version since I wanted to upgrade my logstash version. It looks great, but one questions comes to mind:

There's no archival of old blobs, eg. moving it to a different container etc. We have thousands of logfiles, and looping through them in `list_all_blobs` is going to take a loong time. What is the suggested way of handling this?

**Comment by xiaomi7732** [comment]
@simonwh I see issues from reading your comment.
1. As you pointed out, there's no archival functionality in the plugin. I am leaning toward that is, arguably, not the responsibility of the plug in.
2. You are concern that list_all_blobs is going to take too long enumerating all the blobs. That is totally a legitimate concern. I don't have a direct answer for you but here's my 2 cents:
I think this is a case by case issue because there are various factors that could contribute to the slowness. I would firstly try to use the plugin as is too see how much time will it take - kind of to benchmark it to see how good or how bad it is. If possible, employ some clean up strategies - moving files that is 48 hours ago to cold storage for example.
If you really want to handle the archive, I would look into Logstash to see if there's some/any events that can be make use of to do the job.
I wish this might help you set out to the right direction. Feel free to post back. :-)

**Comment by simonwh** [comment]
@xiaomi7732 Thanks for getting back to me!

I see your point with the archiving not being the responsibility of the plugin. However, it does become a challenge to use the plugin for me because of that. I have ~10 webservices logging into hourly text files, for 3 servers. That's 720 blobs every 24 hours. A few days of blobs and it starts to become an issue, so archival is needed. What you described, archiving/moving blobs after 48 hours, is exactly what my current version does. It's great, and needed, if you're producing a lot of logs.

Feel free to check my [current version](https://gist.github.com/simonwh/b22ea63160b0fd0d6a4cae43072564bf) and see if it's something that would be interesting to implement. In my opinion, the plugin is not really useable without it for any larger production setups.
