### ISSUE TITLE
Delete blobs after consuming them

### ISSUE THREAD

**Issue by alelts** [Azure/azure-diagnostics-tools#75]
Hi there,

is there a way to make logstash delete the blobs after it consumed them?

Thanks

**Comment by brahmnes** [comment]
The azureblob plugin itself would be the best way for that because it's the only one who knows when it finished consuming it. However, you never know if the writer is still writing to that blob or not.
The azureblob plugin currently doesn't do that. There was a PR: https://github.com/Azure/azure-diagnostics-tools/issues/64 a while ago for supporting backupmode which deletes but also copies it.

**Comment by xiaomi7732** [comment]
Deleting blob is not supposed to be done by your logging system.
