### ISSUE TITLE
logstash-input-blob 0.9.8 out of memory error

### ISSUE THREAD

**Issue by EmFl** [Azure/azure-diagnostics-tools#84]
Hello,
I'm testing the new version of the blob input and have a storage account with a couple of month of log content (let's say something like 50000 blobs). 
After a few minute logstash crashes with out of memory error. It is currently running with 3g of heap.
I will try to pinpoint the issue and see what is actually happening (i'm pointing to 4 different containers in two different storage account) but wanted to log the issue in case someone else is already working on this.
Regards

**Comment by xiaomi7732** [comment]
Hi @EmFl,
Thanks for your report. This issue has been identified and will be fixed in 0.9.9. The ETA for the release is by end of this Friday.
If you want to get the bits before that, here's the private PR: #83.

**Comment by xiaomi7732** [comment]
@EmFl,
The fix is released at: https://rubygems.org/gems/logstash-input-azureblob/versions/0.9.9
Please refer [Readme.MD](https://github.com/Azure/azure-diagnostics-tools/blob/master/Logstash/logstash-input-azureblob/README.md) for examples. Specifically, pay attention to the parameter of **blob_list_page_size**.

Thanks,
Saar
